<!DOCTYPE html>
<div style="background-color: #101010; color: white;">
    <head>
  
   <meta charset="UTF-8">
  <meta name="description" content="Безпека в інтернеті сайт по Безпеці на українській мові">
   <title>Безпека в інтернеті</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous"> 
 <link rel=" stylesheet" type="text/css"href="style.css">
 </head>
  <body>
<div class="header" style="background-color: #340047;
    border-bottom: 3px solid #010047;
    padding-top: 12px;
    padding-bottom: 12px;
    color: white;">
    <header class="container">
    <h1 style="font-family: arial;">Вітаємо в безпека в інтернеті
</h1></header>
  </div>
  <form action="https://www.instagram.com/ma.rian724/" method="get"><button type="submit"style="width=:160px:height:40px;">Інстаграм</button></form>  
<form action="https://maksimlink185.github.io/ChporaProgramsta/index.html" method="get"><button type="submit"style="width=:160px:height:40px;">Якщо ви цікаветесь програмуванням</button></form>  
  <img src= "https://i.ytimg.com/vi/--bFR14G0dI/hqdefault.jpg" width="350px" height= "300px">
  <img src="https://lh3.googleusercontent.com/proxy/Fsyl4dMRntkN8xxwHHZ2nUAKw1A24gJIbJymsuFfAaeVnsZzpEaFGyvLMmp67NY2LjK0E8GhTtxxYMva7Rg8s5L51dRkTpoqZWACCk--qHNfgVtfAhNrOHAAkGO2pxc"width="450px" height= "300px"
    </body><p>Привіт я вам розкажу наскільки важлива є сложнісьть пароля.
А ви  знаєш, що хакери можуть зламати доступ до вашого акаунта в будь-яких соцмережах, Facebook чи Instagram?  Вони можуть прочитати ваші повідомлення, вкрасти особисту інформацію, розсилати твоїм друзям хакерські програми і  навіть просити в них гроші від вашого імені? Щоб захистити свої акаунти в соцмережах, увімкни двофакторну верифікацію.
Якщо шахрай зламав один із ваших акаунтів у будь-яких онлайн-сервісах, йому значно легше буде зламати і інші. По-перше, якщо відкрити доступ до вашої електронної скриньки в Google, автоматично можна зайти в усі інші сервіси Google, такі як диск чи YouTube, тому що обліковий запис для них один. 

<p>
<h1>Як   встановити на Google</h1>
На телефоні або планшеті Android відкрийте додаток Налаштування, виберіть Google та перейдіть у Акаунт Google.
У верхній частині екрану натисніть Безпека.
У розділі Вхід до акаунту Google виберіть Двоетапна перевірка.
Натисніть Розпочати та дотримуйтесь інструкцій на екрані, щоб обрати спосіб додаткового підтвердження, наприклад, за допомогою SMS-повідомлення чи через певний додаток</p>.
<p><h2>Для Instagram</h2>
Зайдіть у додаток Instagram.

Натисніть на мініатюру вашого аватару в правому нижньому куті екрану, щоб перейти у свій профіль.

Відкрийте Меню, натиснувши на значок в правому верхньому куті екрану.

Зайдіть у Налаштування та оберіть вкладку Безпека.

Перейдіть у розділ Двоетапна перевірка та дотримуйтесь вказівок на екрані, щоб вказати номер телефону для додаткової верифікації.</p> 
<p><h3>Для Facebook</h3>
Зайдіть у додаток Facebook.

Відкрийте Меню, натиснувши на значок у правому нижньому (для iOS-пристроїв) або у правому верхньому куті екрану (для Android-пристроїв).

У блоці Налаштування та конфіденційність оберіть Налаштування і перейдіть у розділ Безпека та Вхід.

Прокрутіть вниз до розділу Використання двоетапної перевірки і натисніть Редагувати.

Виберіть спосіб аутентифікації, який хочете додати, наприклад, підтвердження за допомогою SMS і дотримуйтесь інструкцій на екрані
<h4>
Оновлення програмного забезпечення<h4> 

Найкращим захистом від вірусів є не антивірусний захист, своєчасне оновлення програмного забезпечення. Адже його розробники слідкують за можливими загрозами і намагаються захистити свої продукти нововведеннями. Тому, коли ваш пристрій пропонує вам оновлення – не ігноруйте це!
Наполегливо рекомендуємо не вводити персональну інформацію (логін, пароль, номер телефону чи платіжної карти) на запити неперевірених сайтів.

Такі дані можна надавати лише тим ресурсам, які вже пройшли вашу перевірку, або відомим мережам (наприклад, Google, Facebook, Rozetka, ваші блоги на інформаційних ресурсах тощо).

І ще – обов’язково перевіряйте назву сайту в адресному рядку браузера (www.google.com.ua а не www.goolge.com.ua).

Вводити ж інформацію з платіжних карток чи паролі від них можна лише на сайтах зі значком «замочка» в адресному рядку. Таке з’єднання вважається захищеним, а ваші дані не потраплять до рук сторонніх осіб.

</p>
1.0.1
</p>
  </body>
</div>
</html>
